feat/table cleanup
project44/manifest-ui pull request #168
Opened 2022-02-28 18:16 UTC by bclark-p44

DES-61: Updating table design to support pagination and sorting.

2022-02-28 19:02 UTC, eemahoney requested changes
Thanks for the updates @brandon-convey 

I pulled and served locally came across a few UX issues to address:

* Sort icons should persist on sortable columns. Team has had a lot of discussion so no worries that this got a bit lost. See my comment and discussion thread [here](https://p-44.slack.com/archives/C02HH1T46UF/p1645744619945949?thread_ts=1645739935.795419&cid=C02HH1T46UF).
* Sorting is not keyboard accessible. Focusing and using the Return key to toggle between asc and desc does not work. (Find a good example of that working from the [W3 Table example](https://w3c.github.io/aria-practices/examples/table/sortable-table.html))
* If keyboard accessible, shouldn't the sortable headers be focusable? I _think_ I am seeing the browser/system default focus ring

<img width="127" alt="Screen Shot 2022-02-28 at 12 46 13 PM" src="https://user-images.githubusercontent.com/88858003/156041874-ca408c42-98a8-4c84-9c81-eae0faf77a4f.png">

Other things to note, perhaps out of the scope of this work:

Shouldn't we have a scroll bar if the table width goes beyond the screen? Currently I'm seeing this when minimizing the screen and I do not have the ability to scroll over to the right end of the table.

<img width="491" alt="Screen Shot 2022-02-28 at 12 57 04 PM" src="https://user-images.githubusercontent.com/88858003/156042155-69e066f5-3fc5-4c4f-bd62-fea78e954a22.png">

2022-02-28 19:12 UTC, eemahoney commented
For Storybook, are we only supposed to see these available props in the Controls panel?
<img width="1245" alt="Screen Shot 2022-02-28 at 1 11 12 PM" src="https://user-images.githubusercontent.com/88858003/156044019-ba5a2617-0543-4f3f-a60e-44994c058c53.png">

2022-02-28 19:27 UTC, eemahoney commented
![Feb-28-2022 13-14-26](https://user-images.githubusercontent.com/88858003/156044379-bef95b29-a5f8-4f64-a08c-d3b45cc684b6.gif)

Confirming the width change when an icon is added to a header

2022-02-28 19:47 UTC, bclark-p44 commented on packages/table/src/TableFooter.tsx
> +      <StyledTableFooter className="manifestui-table-footer" ref={ref} {...props} />
we can override styles via the theme, but this allows for inline overrides via the `sx` prop if a consumer wants.

2022-02-28 19:47 UTC, bclark-p44 commented on packages/color/package.json
> +  "dependencies": {
nope, these are regular dependencies

2022-02-28 19:48 UTC, bclark-p44 commented on .storybook/addons/styled/enhancers.js
> +const formatStyledProps = ({ argTypes }) => {
We could definitely extend this out in the future. For now, I went with the simplest implementation. I will add some comments

2022-02-28 19:55 UTC, bclark-p44 commented
@eemahoney 

> For Storybook, are we only supposed to see these available props in the Controls panel?

Those are the only props that extend the native element props. I thought we didn't want to list every HTML prop in this table?

> Confirming the width change when an icon is added to a header

Yes, the sort icon adds width to the header. I can make it absolute and not extend the width if we'd like.

For keyboard accessibility that should be easy enough to add, although we need a design for that. Do we want the whole cell to be focusable? or just the sort button (the text and the icon). If we go the whole-cell route, we are getting into data-grid territory. 

> Shouldn't we have a scroll bar if the table width goes beyond the screen? Currently, I'm seeing this when minimizing the screen and I do not have the ability to scroll over to the right end of the table.

I think we need to decide on paradigms for horizontal scrolling, do we want just the body / header to scroll? Does that include the footer? What about if the footer is pagination?

2022-02-28 23:05 UTC, bclark-p44 commented
@eemahoney just going to re-hash what we discussed IRL here on the ticket for transparency:

1. For storybook we can't get rid of the `docs` tabs completely because of the need to document sub-component APIs. There is a limitation in SB that will not add sub-component props to the `controls` section in canvas, requiring us to keep this tab around.
2. Design is through the following: Header icon width (whether it should add to the width or not), keyboard accessibility rules, focus states for column sort button, table width, and horizontal scrolling.

For those reasons above, we are going to hold off on merging / making updates to this PR until we've had time to consider some of the lingering questions/discrepancies between design and development.

2022-03-02 14:12 UTC, eemahoney commented
Pull and confirmed new changes. Good stuff @brandon-convey, thank you

2022-03-02 14:13 UTC, eemahoney submitted a review, later dismissed

2022-03-02 14:57 UTC, bclark-p44 commented on .storybook/addons/styled/enhancers.js
> +const formatStyledProps = ({ argTypes }) => {
@eemahoney added some comments here.

2022-03-02 19:15 UTC, eemahoney commented
<img width="562" alt="Screen Shot 2022-03-02 at 1 12 33 PM" src="https://user-images.githubusercontent.com/88858003/156432233-09b3aff7-915f-4c81-add4-441c83b16079.png">

I might be asking the wrong question but should header cells have a min width? Is this expected? with the header and sorting icon in my screenshot?

2022-03-02 20:39 UTC, eemahoney approved these changes
Thank you for all the hard work on this table @bclark-p44 . Let's :shipit:

2022-03-02 20:41 UTC, merged